version: '3.8'
services:
  cashregisterapi:
    image: ${DOCKER_REGISTRY-}cashregisterapi
    build:
      context: .
      dockerfile: CashRegister.API/Dockerfile
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=master;User=sa;Password=Password123@;"
    depends_on:
      - sqlserver
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "Password123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
